# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Everything < Formula
  desc "Dump your entire project into a single file. Mostly for feeding code to LLMs."
  homepage "https://github.com/Hxmbl/everything"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hxmbl/everything/releases/download/v1.1.0/everything_1.1.0_Darwin_x86_64.tar.gz"
      sha256 "50b34795c4c74648e6d9917f577ffd9c3d84cb1895470574c4c840dcc8eb1ef6"

      define_method(:install) do
        bin.install "everything"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hxmbl/everything/releases/download/v1.1.0/everything_1.1.0_Darwin_arm64.tar.gz"
      sha256 "bdcb711ded801088400c10f6af1ae9125d89ebdd9106963b0d52dc4217490260"

      define_method(:install) do
        bin.install "everything"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hxmbl/everything/releases/download/v1.1.0/everything_1.1.0_Linux_x86_64.tar.gz"
      sha256 "ac7fdfb69cf6d2828d725837fe9bc46c150620e5aff28f0367102ef9ecaacb2b"
      define_method(:install) do
        bin.install "everything"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hxmbl/everything/releases/download/v1.1.0/everything_1.1.0_Linux_arm64.tar.gz"
      sha256 "659b958747fa4601b58b50c9aef94ab7b2aa85b834e1405198fa6a25ee217210"
      define_method(:install) do
        bin.install "everything"
      end
    end
  end

  test do
    system "#{bin}/everything --version"
  end
end
